### ISSUE TITLE
does not send event when value is `null`

### ISSUE THREAD

**Issue by b-ma** [collective-soundworks/soundworks-state-manager-osc#20]

**Comment by etiennedemoulin** [comment]
can you explain ? works for me on "any" and "message" types.

**Comment by etiennedemoulin** [comment]
dict.deserialize understand only strings

**Comment by etiennedemoulin** [comment]
at reception in max , before dict.deserialise, check for null with js function

**Comment by etiennedemoulin** [comment]
@b-ma in fact null is well written in the dict object, but dict.view don't support it.
to see it you can create a dict globals_values object and open it
